name: Run_Move_Prover

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        fetch-depth: 50 # this is to make sure we obtain the target base commit
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR

    - name: Detect the changes in move-prover
      working-directory: ./libra
      env:
        BASE: ${{ github.event.client_payload.base_ref }}
        PULL_ID: ${{ github.event.client_payload.pull_id }}
      run: |
        echo Test requested by https://github.com/libra/libra/pull/$PULL_ID
        git diff --name-only $BASE
        if (git diff --name-only $BASE | grep "language/move-prover\|language/move-lang/src\|language/stdlib\|language/bytecode-verifier/src\|language/vm/src")
        then
          echo "::set-env name=RUN_TEST::yes"
        else
          echo "::set-env name=RUN_TEST::no"
        fi

    - name: Install Z3
      if: env.RUN_TEST == 'yes'
      uses: pavpanchekha/setup-z3@v1.2
      with:
        version: "4.8.7"

    - name: Install .NET Core SDK and Boogie
      if: env.RUN_TEST == 'yes'
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1
        dotnet tool install --global Boogie --version 2.5.7

    - name: Export the environment variables
      if: env.RUN_TEST == 'yes'
      run: |
        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
        echo "::set-env name=Z3_EXE::`which z3`"
        echo "::set-env name=JOB_INS_ID::`curl -s https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID | egrep '/[0-9]{9}\?' -o | egrep '[0-9]{9}' -o`"

