name: Run_Move_Coverage

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  run_Move_coverage:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        fetch-depth: 50 # this is to make sure we obtain the target base commit
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR

    - name: Detect the changes in the Move stdlib and tests
      working-directory: ./libra
      env:
        BASE: ${{ github.event.client_payload.base_ref }}
        PULL_ID: ${{ github.event.client_payload.pull_id }}
      run: |
        echo Coverage report requested by https://github.com/libra/libra/pull/$PULL_ID
        git diff --name-only $BASE
        if (git diff --name-only $BASE | grep "language/move-lang/tests/functional\|language/ir-testsuite\|language/stdlib\|language/e2e-tests")
        then
          echo "::set-env name=RUN_TEST::yes"
          echo "::set-env name=MOVE_VM_TRACE::$HOME/trace"
        else
          echo "::set-env name=RUN_TEST::no"
        fi

    - name: Run Move coverage report
      if: env.RUN_TEST == 'yes'
      id: run_move_coverage
      working-directory: ./libra/language/tools/move-coverage
      timeout-minutes: 30 # normally, expected to be done within 10 mins.
      run: |
        set -o pipefail
        if (gather_stats.bash 2>&1 | tee /home/coverage_report.log)
        then
          echo "::set-env name=TEST_RESULT::pass"
          exit 0
        else
          err=$?
          echo "::set-env name=TEST_RESULT::fail"
          exit $err
        fi

    - name: Post the coverage report as a comment
      if: env.RUN_TEST == 'yes'
      uses: actions/github-script@0.6.0
      env:
        PULL_ID: ${{ github.event.client_payload.pull_id }}
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
      with:
        github-token: ${{secrets.MIRAI_BOT}}
        script: |
          const fs = require('fs');
          test_result = (process.env.TEST_RESULT == undefined) ? 'timeout (> 30 mins)' : process.env.TEST_RESULT;

          if (process.env.JOB_INS_ID.length == 9) {
            link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/runs/${process.env.JOB_INS_ID}?check_suite_focus=true#step:7:1`;
          }
          else {
            link_to_log=`https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
          }

          fs.readFile('/home/coverage_report.log', (err, data) => {
              if err throw err;
              var message = `Hey you!

              Here is the Move coverage report

              <details><summary>click here to reveal it</summary>
              <pre><code>${data}</code></pre>
              </details>

              You can get more details here: ${link_to_log}

          `;
          console.log(message);
          })
