name: Move_Coverage

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  run_Move_coverage:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        fetch-depth: 50 # this is to make sure we obtain the target base commit
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR

    - name: Detect the changes in the Move stdlib and tests
      working-directory: ./libra
      env:
        BASE: ${{ github.event.client_payload.base_ref }}
        PULL_ID: ${{ github.event.client_payload.pull_id }}
      run: |
        echo Coverage report requested by https://github.com/libra/libra/pull/$PULL_ID
        git diff --name-only $BASE
        if (git diff --name-only $BASE | grep "language/move-lang/tests/functional\|language/ir-testsuite\|language/stdlib\|language/e2e-tests")
        then
          echo "::set-env name=RUN_TEST::yes"
          echo "::set-env name=MOVE_VM_TRACE::$HOME/trace"
        else
          echo "::set-env name=RUN_TEST::no"
        fi
