name: Test_Move_Prover

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-18.04
  
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Checkout libra
      env:
        HELLO: WORLD
        HI: ${{ 'THERE' }}
      uses: actions/checkout@v2
      with:
        path: "libra"
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
    - name: Detect the changes in move-prover
      working-directory: ./libra
      env:
        BASE: ${{ github.event.client_payload.base_ref }}
        REF: ${{ env.HELLO }}
      run: |
        echo $HELLO
        echo $REF
        echo $HI
        git diff --name-only $BASE
        git diff --name-only $BASE | grep "language/move-prover"
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
      with:
        version: "4.8.7"
    - name: Install .NET Core SDK and Boogie
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1
        dotnet tool install --global Boogie --version 2.5.7
    - name: Export the environment variables
      run: |
        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
        echo "::set-env name=Z3_EXE::`which z3`"
    - name: Test move-prover
      id: test_move_prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      timeout-minutes: 20 # normally, expected to be done within 10 mins.
      run: |
        set -o pipefail
        cargo test 2>&1 | tee cargo_test.log
    - name: Comment the error message if the test failed
      if: failure()
      uses: actions/github-script@0.5.0
      env:
        PULL_ID: ${{ github.event.client_payload.pull_id }}
        COMMENTING: ${{ 'no' }}
      with:
        github-token: ${{secrets.MIRAI_BOT}}
        script: |
          const fs = require('fs');
          fs.readFile('libra/language/move-prover/bytecode-to-boogie/cargo_test.log', 'utf-8', async (err, data) => {
            if (err) {
              console.log("err:", err);
              console.log("`cargo test` has not launched. Perhaps, it was skipped because no changes under `language/move-prover` were found.");
              throw "No changes under `language/move-prover` were found.";
              return;
            }
            if (!data) {
              return;
            }
            console.log("Move Prover test failed on https://github.com/libra/libra/pull/" + process.env.PULL_ID);

            lines = data.split('\n');
            data = lines.slice(lines.findIndex(line => line.includes('Running'))).join('\n');
            data = "[move-prover] `cargo test` for Move Prover (`language/move-prover/bytecode-to-boogie`) failed with the following error message: \n```\n" + data + "\n```";    

            console.log('Message to send: \n' + data);

            console.log(process.env.COMMENTING);
            console.log(env.BOOGIE_EXE);
            console.log(env.Z3_EXE);

            console.log(`https://github.com/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}`);
            throw "Move Prover test failed.";
          })



        # GITHUB_WORKFLOW_URL=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

        # if(process.env.COMMENTING == 'yes') {
        #   await github.issues.createComment({
        #       owner: "libra",
        #       repo: "libra",
        #       issue_number: process.env.PULL_ID,
        #       body: data
        #     });
        #   }
        # }
