name: Test_Move_Prover

on:
  repository_dispatch:
    types: [new_PR]

jobs:
  install_and_test_Move_Prover:

    runs-on: ubuntu-latest

    steps:
    - name: Install Z3
      uses: pavpanchekha/setup-z3@v1.2
    - name: Install .NET Core SDK and Boogie
      run: |
        sudo apt-get update
        sudo apt-get install apt-transport-https
        sudo apt-get update
        sudo apt-get install dotnet-sdk-3.1
        dotnet tool install --global Boogie
    - name: Export the environment variables
      run: |
        echo "::set-env name=BOOGIE_EXE::/home/runner/.dotnet/tools/boogie"
        echo "::set-env name=Z3_EXE::`which z3`"
    - name: Checkout libra
      uses: actions/checkout@v2
      with:
        path: "libra"
        fetch-depth: 50 # this is to make sure we obtain the target base commit
        repository: ${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }} # repo of the forked libra/libra
        ref: ${{ github.event.client_payload.pull_ref }} # commit that triggered the PR
    - name: Build move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      run: cargo build
    - name: Test move-prover
      working-directory: ./libra/language/move-prover/bytecode-to-boogie
      timeout-minutes: 10 # normally, expected to be done within 1 min.
      run: cargo test
